### ISSUE TITLE
Cannot send request: wrong discovery rule type.

### ISSUE THREAD

**Issue by KingHorse2015** [Cosium/zabbix_zfs-on-linux#11]
When hitting the check now button, I get a error message that it has a wrong discorvery rule type.

Zabbix version: 4.2.8

I have follewed the setup guide. I checked every step it is all in place.

But maybe I missed something?

**Comment by AceSlash** [comment]
Hey @KingHorse2015 , 

Unfortunately I currently don't have access to a Zabbix agent version 4.2.8, but could you try to test the discovery rule directly on the agent?

To do that, try those commands:
```
zabbix_agentd -t zfs.pool.discovery
zabbix_agentd -t zfs.fileset.discovery
zabbix_agentd -t zfs.vdev.discovery
```
Every commands should return a JSON with the discovered items.

**Comment by lightelfua** [comment]
zabbix_agentd -t zfs.pool.discovery
zfs.pool.discovery                            [t|{ "data":[{"{#POOLNAME}":"storage-pool"}]}]

zabbix_agentd -t zfs.fileset.discovery
zfs.fileset.discovery                         [t|{ "data":[{"{#FILESETNAME}":"storage-pool"},
{"{#FILESETNAME}":"storage-pool/raid"}]}]

zabbix_agentd -t zfs.vdev.discovery
zfs.vdev.discovery                            [t|{ "data":[{"{#VDEV}":"sdb"},
{"{#VDEV}":"sdc"},
{"{#VDEV}":"sdd"},
{"{#VDEV}":"sde"},
{"{#VDEV}":"sdf"},
{"{#VDEV}":"sdg"}]}]

**Comment by AceSlash** [comment]
Ok great, active checks need the correct hostname as you just noticed ;-)

Closing.
