### ISSUE TITLE
Global regular expression "ZFS fileset" does not exist.

### ISSUE THREAD

**Issue by victor-sudakov** [Cosium/zabbix_zfs-on-linux#22]
Hello, I've just created a global regular expression "ZFS fileset" but the "Zfs Dataset Discovery" still says that

"Global regular expression "ZFS fileset" does not exist."

What else am I missing? Zabbix 5.0.7

![image](https://user-images.githubusercontent.com/12457866/103126141-ed5e2500-46bf-11eb-9f8d-a9eac6fd1098.png)

![image](https://user-images.githubusercontent.com/12457866/103126185-17174c00-46c0-11eb-8d5a-31e505ddb81e.png)

**Comment by AceSlash** [comment]
It should be good, do you still have the issue? Since the LLD happens once every 30 minutes, if you created the "Global regular expression" after you imported the template, you can have the issue first and it will go away after 30 minutes when the next LLD will run.

**Comment by victor-sudakov** [comment]
I forced the LLD manually (the "Execute now" button) several times, but the error was still showing. Eventually the error cleared. It looks like there is something which is not applied immediately even when "Execute now" is forced.

**Comment by AceSlash** [comment]
@victor-sudakov : in the end, I removed the global expression completely, so this will not happen anymore. The installation is also simpler now :-)
